application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /home/serine/website/stylesheets
  static_dir: stylesheets

- url: /.*
  script: templates.application

libraries:
- name: jinja2
  version: latest
